# Generated by Django 5.2 on 2025-05-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminders',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
